spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
#    url: jdbc:h2:tcp://localhost:1521/opt/h2-data/jpashop
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.sql: debug
#    org.hibernate.type: trace

